### PR TITLE
Customer history

### PR DESCRIPTION
**Pull request by KrasimirRaikov**
Two tables customer and customer_history, when the customer table is updated the current information is recorder to the customer_history table.

### CODE REVIEW

**Comment by KrasimirRaikov** [comment]
devided the resposibilities of `PersistentCustomerRepository`, making `PersistentCustomerHistoryRepository`

**Comment by KrasimirRaikov** [comment]
made the `id` of type `long`

**Comment by panayotkulchev** [comment]
I thing in any of your PRs I told you that labels like `needs review` were added. Even you assigned me this do not means that the PR is for review. This means that I will make the code review. When you put 'needs review' I can understand that all notes are fixed and can start review your code. This is how we do it in real projects

**Comment by panayotkulchev** [comment]
LGTM

**Pull request merged**
